name: "Señorita"
owner: "Chiu"
avatar: "/assets/images/avatar_cat.jpg"
description: "The name is Chiu and this is my personal web site. I see myself as a relentless problem-solver, and I’m always looking for a new challenge."
url: "https://LaSenhorita.github.io/Ignition"

path:
  assets: "/assets"
  images: "/assets/images"
  css: "/assets/css"
  js: "/assets/js"

highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

permalink: /posts/:title/

sass:
  sass_dir: "/assets/css/"
  style: compressed

# Plugins
plugins: [jekyll-paginate,jekyll-toc,liquid] #,jekyll-asciidoc]
paginate: 15
paginate_path: "/posts/page/:num"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: "post"
